---
- name: Install software on Windows using Chocolatey
  hosts: windows
  gather_facts: no
  tasks:
    - name: Ensure Chocolatey is installed
      win_shell: |
        Set-ExecutionPolicy Bypass -Scope Process -Force
        [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12
        Invoke-Expression ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
      args:
        executable: powershell

    - name: Install Google Chrome
      win_chocolatey:
        name: googlechrome
        state: present

    - name: Install Notepad++
      win_chocolatey:
        name: notepadplusplus
        state: present

    - name: Install 7-Zip
      win_chocolatey:
        name: 7zip
        state: present
